import { createContext } from 'react'

export const LANGUAGE_KEY = 'skillquest.language'

export const LanguageContext = createContext(null)

export const messages = {
  en: {
    home: 'My Learning Space', quests: 'My Quests', progress: 'Learning Progress', explore: 'Explore', news: 'News', leaderboard: 'Leaderboard', achievements: 'Achievements', learningPath: 'Learning Path', settings: 'Settings', help: 'Help & Support', search: 'Search', notifications: 'Notifications', profile: 'Profile',
    welcomeBrand: 'Welcome to SkillQuest 👋', landingTitle: 'Turn learning into a quest.', landingDescription: "Choose your class, interests and goals. We'll create a learning experience made for you.", getStarted: 'Get Started →', alreadyAccount: 'Already have an account?', signIn: 'Sign In', startLearning: 'Start Learning', exploreQuests: 'Explore Quests', onboardingIntroTitle: "Let's build your learning path.", onboardingIntroSubtitle: 'Four quick steps. Then your first quests are ready.', welcomeToday: "Here's what you can learn today.",
    registerTitle: 'Create your SkillQuest account', registerSubtitle: 'Your learning journey starts here.', registerName: 'Full name', registerUsername: 'Username', registerEmail: 'Email address', registerPassword: 'Password', registerConfirm: 'Confirm password', registerCreate: 'Create account', registerTerms: 'I agree to the Terms of Service and Privacy Policy.',
    stepClassTitle: 'Which class are you in?', stepClassSubtitle: 'This helps us show you the right learning content.', stepClassWhy: 'Your class helps us match the challenge to you.', stepInterestsTitle: 'What are you interested in?', stepInterestsSubtitle: 'Choose a few topics you would enjoy exploring.', stepGoalsTitle: 'What do you want to achieve?', stepGoalsSubtitle: 'Choose every goal that matters to you.', stepReadyTitle: 'Your SkillQuest path is ready! 🚀', stepReadySubtitle: "Based on your class, interests and goals, we've prepared your first quests.", stepProfile: 'YOUR PROFILE', className: 'Class', stepInterests: 'Interests', stepGoal: 'Goals', firstQuests: 'Your first quests', firstQuestsEmpty: 'Add a learning subject to see recommended quests.', enterLearningSpace: 'Enter My Learning Space', continue: 'Continue', back: 'Back', createPath: 'Create My Learning Path', stepCounter: 'Step {step} of 4', selectGrade: 'Select a class to continue.', selectInterest: 'Choose at least one interest.', selectGoal: 'Choose at least one goal.',
    classJunior: 'Grades 1–4', classExplorer: 'Grades 5–8', classPro: 'Grades 9–11', gradeName: '{grade}th Grade', interestsProgramming: 'Programming', interestsEnglish: 'English', interestsMath: 'Mathematics', interestsScience: 'Science', interestsDesign: 'Design', interestsBusiness: 'Business', interestsCritical: 'Critical Thinking', interestsCommunication: 'Communication', interestsGeneral: 'General Knowledge',
    goalGrades: 'Improve my grades', goalSkill: 'Learn a new skill', goalCompetition: 'Prepare for competitions', goalProgrammer: 'Become a programmer', goalEnglish: 'Improve my English', goalCareer: 'Prepare for my future career',
    errorName: 'Please enter your full name.', errorUsername: 'Choose a username to continue.', errorEmail: 'Please enter your email address.', errorEmailInvalid: 'Enter a valid email address.', errorPassword: 'Use at least 8 characters.', errorPasswordUpper: 'Add at least one uppercase letter.', errorPasswordNumber: 'Add at least one number.', errorConfirm: 'Please confirm your password.', errorPasswordMatch: 'Your passwords do not match.', errorAgreement: 'Please agree to continue.',
    mySpace: 'MY SPACE', discover: 'DISCOVER', myJourney: 'MY JOURNEY', signOut: 'Sign out', welcomeBack: 'Welcome back', welcomeSubtitle: 'Keep learning, complete quests, and build your future.', exploreTitle: 'Find what sparks your curiosity', exploreSubtitle: 'Choose a learning path or jump into a quest that fits your momentum.', questsTitle: 'Choose your next challenge', questsSubtitle: 'Practice a skill, earn XP, and keep building your learning streak.', newsTitle: 'News & ideas', newsSubtitle: 'Fresh perspectives to fuel your next learning quest.', leaderboardSubtitle: 'Celebrate the quests, practice, and progress that add up.', achievementsSubtitle: 'Every badge marks a skill, streak, or moment of progress.', profileSubtitle: 'Your progress, practice, and milestones in one place.', progressSubtitle: 'Every completed quest builds a skill you can keep.', searchTitle: 'Search SkillQuest', searchSubtitle: 'Find a quest to try or an idea to explore.', browseQuests: 'Browse quests', allQuests: 'All quests', all: 'All', english: 'English', programming: 'Programming', mathematics: 'Mathematics', science: 'Science', design: 'Design', business: 'Business', generalSkills: 'General Skills', beginner: 'Beginner', intermediate: 'Intermediate', advanced: 'Advanced',
    settingsTitle: 'Settings', settingsSubtitle: 'Make SkillQuest work the way you learn.', profileDetails: 'Profile details', profileDetailsHelp: 'Update the name shown around SkillQuest.', appearance: 'Appearance', appearanceHelp: 'Choose a comfortable palette for your learning space.', language: 'Language', languageHelp: 'Your language preference is saved on this device.', darkMode: 'Dark mode', lightMode: 'Light mode', saveProfile: 'Save profile', name: 'Full name', username: 'Username', saved: 'Your settings have been saved.',
    helpTitle: 'Help & Support', helpSubtitle: 'Quick answers for your learning journey.', helpNeed: 'Need a hand?', helpContactAdvice: 'For account or classroom support, speak with your teacher or school administrator.', helpReviewSettings: 'Review settings', faqQuestTitle: 'How do quests work?', faqQuestBody: 'Choose a subject in your learning path, open a quest, and submit your answer to earn XP and update your progress.', faqStorageTitle: 'Where is my progress saved?', faqStorageBody: 'Your profile, XP, streak, and completed quests are stored locally in this browser on this device.', faqPathTitle: 'Can I change my learning path?', faqPathBody: 'Yes. Open Learning Path from the sidebar to update your grade, subjects, interests, and learning goal.', emptyNotifications: 'No notifications yet', clearNotifications: 'Clear all', markRead: 'Mark all as read', newsEducation: 'Education', newsTechnology: 'Technology', newsScience: 'Science', newsProgramming: 'Programming', newsEnglish: 'English', newsStudyTips: 'Study Tips', readMore: 'Read More',
  },
  uz: {
    home: 'Mening o‘quv makonim', quests: 'Mening questlarim', progress: 'O‘quv natijalari', explore: 'Kashf etish', news: 'Yangiliklar', leaderboard: 'Reyting', achievements: 'Yutuqlar', learningPath: 'O‘quv yo‘li', settings: 'Sozlamalar', help: 'Yordam', search: 'Qidirish', notifications: 'Bildirishnomalar', profile: 'Profil',
    welcomeBrand: 'SkillQuest’ga xush kelibsiz 👋', landingTitle: 'O‘rganishni questga aylantiring.', landingDescription: 'Sinfingiz, qiziqishlaringiz va maqsadlaringizni tanlang. Sizga mos o‘quv tajribasini yaratamiz.', getStarted: 'Boshlash →', alreadyAccount: 'Hisobingiz bormi?', signIn: 'Kirish', startLearning: 'O‘rganishni boshlash', exploreQuests: 'Questlarni ko‘rish', onboardingIntroTitle: 'O‘quv yo‘lingizni yarataylik.', onboardingIntroSubtitle: 'To‘rtta qisqa qadam. So‘ng ilk questlaringiz tayyor bo‘ladi.', welcomeToday: 'Bugun nima o‘rganishingiz mumkinligini ko‘ramiz.',
    registerTitle: 'SkillQuest hisobini yarating', registerSubtitle: 'O‘quv safaringiz shu yerdan boshlanadi.', registerName: 'To‘liq ism', registerUsername: 'Foydalanuvchi nomi', registerEmail: 'Elektron pochta', registerPassword: 'Parol', registerConfirm: 'Parolni tasdiqlang', registerCreate: 'Hisob yaratish', registerTerms: 'Foydalanish shartlari va Maxfiylik siyosatiga roziman.',
    stepClassTitle: 'Nechanchi sinfda o‘qiysiz?', stepClassSubtitle: 'Bu sizga mos o‘quv materiallarini ko‘rsatishga yordam beradi.', stepClassWhy: 'Sinfingiz qiyinchilik darajasini sizga moslaydi.', stepInterestsTitle: 'Nimalarga qiziqasiz?', stepInterestsSubtitle: 'O‘rganishni istagan mavzularingizni tanlang.', stepGoalsTitle: 'Nimaga erishmoqchisiz?', stepGoalsSubtitle: 'Siz uchun muhim bo‘lgan barcha maqsadlarni tanlang.', stepReadyTitle: 'SkillQuest yo‘lingiz tayyor! 🚀', stepReadySubtitle: 'Sinfingiz, qiziqishlaringiz va maqsadlaringizga ko‘ra ilk questlaringizni tayyorladik.', stepProfile: 'SIZNING PROFILINGIZ', className: 'Sinf', stepInterests: 'Qiziqishlar', stepGoal: 'Maqsadlar', firstQuests: 'Birinchi questlaringiz', firstQuestsEmpty: 'Tavsiya etilgan questlarni ko‘rish uchun o‘quv fanini qo‘shing.', enterLearningSpace: 'O‘quv makonimga kirish', continue: 'Davom etish', back: 'Orqaga', createPath: 'O‘quv yo‘limni yaratish', stepCounter: '4 qadamdan {step}-qadam', selectGrade: 'Davom etish uchun sinfni tanlang.', selectInterest: 'Kamida bitta qiziqishni tanlang.', selectGoal: 'Kamida bitta maqsadni tanlang.',
    classJunior: '1–4-sinflar', classExplorer: '5–8-sinflar', classPro: '9–11-sinflar', gradeName: '{grade}-sinf', interestsProgramming: 'Dasturlash', interestsEnglish: 'Ingliz tili', interestsMath: 'Matematika', interestsScience: 'Fan', interestsDesign: 'Dizayn', interestsBusiness: 'Biznes', interestsCritical: 'Tanqidiy fikrlash', interestsCommunication: 'Muloqot', interestsGeneral: 'Umumiy bilimlar',
    goalGrades: 'Baholarimni yaxshilash', goalSkill: 'Yangi ko‘nikma o‘rganish', goalCompetition: 'Musobaqalarga tayyorlanish', goalProgrammer: 'Dasturchi bo‘lish', goalEnglish: 'Ingliz tilimni yaxshilash', goalCareer: 'Kelajakdagi kasbimga tayyorlanish',
    errorName: 'To‘liq ismingizni kiriting.', errorUsername: 'Davom etish uchun foydalanuvchi nomini tanlang.', errorEmail: 'Elektron pochtangizni kiriting.', errorEmailInvalid: 'To‘g‘ri elektron pochta kiriting.', errorPassword: 'Kamida 8 ta belgi kiriting.', errorPasswordUpper: 'Kamida bitta katta harf qo‘shing.', errorPasswordNumber: 'Kamida bitta raqam qo‘shing.', errorConfirm: 'Parolni tasdiqlang.', errorPasswordMatch: 'Parollar mos kelmadi.', errorAgreement: 'Davom etish uchun rozilik bering.',
    mySpace: 'MENING MAKONIM', discover: 'KASHF ETISH', myJourney: 'MENING SAFARIM', signOut: 'Chiqish', welcomeBack: 'Qaytganingiz bilan', welcomeSubtitle: 'O‘rganishda davom eting, questlarni bajaring va kelajagingizni quring.', exploreTitle: 'Qiziqishingizni uyg‘otadigan yo‘nalishni toping', exploreSubtitle: 'O‘quv yo‘lini tanlang yoki hozirgi sur’atingizga mos questni boshlang.', questsTitle: 'Keyingi chaqiruvingizni tanlang', questsSubtitle: 'Ko‘nikma mashq qiling, XP oling va o‘quv zanjiringizni davom ettiring.', newsTitle: 'Yangiliklar va g‘oyalar', newsSubtitle: 'Keyingi o‘quv questingiz uchun yangi qarashlar.', leaderboardSubtitle: 'Questlar, mashqlar va o‘sish natijalarini nishonlang.', achievementsSubtitle: 'Har bir nishon ko‘nikma, davomiylik yoki yutuqni bildiradi.', profileSubtitle: 'O‘sish, mashqlar va yutuqlaringiz bir joyda.', progressSubtitle: 'Har bir bajarilgan quest kelajakda kerak bo‘ladigan ko‘nikmani mustahkamlaydi.', searchTitle: 'SkillQuest’dan qidiring', searchSubtitle: 'Quest yoki o‘rganishga oid g‘oyani toping.', browseQuests: 'Questlarni ko‘rish', allQuests: 'Barcha questlar', all: 'Barchasi', english: 'Ingliz tili', programming: 'Dasturlash', mathematics: 'Matematika', science: 'Fan', design: 'Dizayn', business: 'Biznes', generalSkills: 'Umumiy ko‘nikmalar', beginner: 'Boshlang‘ich', intermediate: 'O‘rta', advanced: 'Yuqori',
    settingsTitle: 'Sozlamalar', settingsSubtitle: 'SkillQuest’ni o‘rganish uslubingizga moslang.', profileDetails: 'Profil ma’lumotlari', profileDetailsHelp: 'SkillQuest’da ko‘rinadigan ismingizni yangilang.', appearance: 'Ko‘rinish', appearanceHelp: 'O‘quv makoningiz uchun qulay rang uslubini tanlang.', language: 'Til', languageHelp: 'Til tanlovi ushbu qurilmada saqlanadi.', darkMode: 'Tungi rejim', lightMode: 'Kunduzgi rejim', saveProfile: 'Profilni saqlash', name: 'To‘liq ism', username: 'Foydalanuvchi nomi', saved: 'Sozlamalar saqlandi.',
    helpTitle: 'Yordam va qo‘llab-quvvatlash', helpSubtitle: 'O‘quv safaringiz uchun qisqa javoblar.', helpNeed: 'Yordam kerakmi?', helpContactAdvice: 'Hisob yoki sinf bo‘yicha yordam uchun o‘qituvchingiz yoki maktab ma’muriga murojaat qiling.', helpReviewSettings: 'Sozlamalarni ko‘rish', faqQuestTitle: 'Questlar qanday ishlaydi?', faqQuestBody: 'O‘quv yo‘lingizdan fan tanlang, questni oching va XP hamda progress olish uchun javob yuboring.', faqStorageTitle: 'Progressim qayerda saqlanadi?', faqStorageBody: 'Profil, XP, streak va bajarilgan questlar ushbu qurilmadagi brauzerda saqlanadi.', faqPathTitle: 'O‘quv yo‘limni o‘zgartira olamanmi?', faqPathBody: 'Ha. Sinf, fanlar, qiziqishlar va maqsadni o‘zgartirish uchun yon menyudan O‘quv yo‘lini oching.', emptyNotifications: 'Hozircha bildirishnomalar yo‘q', clearNotifications: 'Hammasini tozalash', markRead: 'Hammasini o‘qilgan deb belgilash', newsEducation: 'Ta’lim', newsTechnology: 'Texnologiya', newsScience: 'Fan', newsProgramming: 'Dasturlash', newsEnglish: 'Ingliz tili', newsStudyTips: 'O‘qish bo‘yicha maslahatlar', readMore: 'Batafsil',
  },
  ru: {
    home: 'Моё обучение', quests: 'Мои квесты', progress: 'Мой прогресс', explore: 'Обзор', news: 'Новости', leaderboard: 'Рейтинг', achievements: 'Достижения', learningPath: 'План обучения', settings: 'Настройки', help: 'Помощь', search: 'Поиск', notifications: 'Уведомления', profile: 'Профиль',
    welcomeBrand: 'Добро пожаловать в SkillQuest 👋', landingTitle: 'Превратите обучение в квест.', landingDescription: 'Выберите класс, интересы и цели. Мы создадим обучение специально для вас.', getStarted: 'Начать →', alreadyAccount: 'Уже есть аккаунт?', signIn: 'Войти', startLearning: 'Начать обучение', exploreQuests: 'Посмотреть квесты', onboardingIntroTitle: 'Создадим ваш план обучения.', onboardingIntroSubtitle: 'Четыре простых шага, и первые квесты готовы.', welcomeToday: 'Вот что вы можете изучить сегодня.',
    registerTitle: 'Создайте аккаунт SkillQuest', registerSubtitle: 'Ваш путь к новым знаниям начинается здесь.', registerName: 'Полное имя', registerUsername: 'Имя пользователя', registerEmail: 'Электронная почта', registerPassword: 'Пароль', registerConfirm: 'Подтвердите пароль', registerCreate: 'Создать аккаунт', registerTerms: 'Я принимаю Условия использования и Политику конфиденциальности.',
    stepClassTitle: 'В каком вы классе?', stepClassSubtitle: 'Так мы подберём подходящие учебные материалы.', stepClassWhy: 'Класс помогает подобрать подходящую сложность заданий.', stepInterestsTitle: 'Что вам интересно?', stepInterestsSubtitle: 'Выберите темы, которые хотите изучать.', stepGoalsTitle: 'Чего вы хотите достичь?', stepGoalsSubtitle: 'Выберите все важные для вас цели.', stepReadyTitle: 'Ваш путь SkillQuest готов! 🚀', stepReadySubtitle: 'Мы подготовили первые квесты с учётом класса, интересов и целей.', stepProfile: 'ВАШ ПРОФИЛЬ', className: 'Класс', stepInterests: 'Интересы', stepGoal: 'Цели', firstQuests: 'Ваши первые квесты', firstQuestsEmpty: 'Добавьте предмет, чтобы увидеть подходящие квесты.', enterLearningSpace: 'Перейти к обучению', continue: 'Продолжить', back: 'Назад', createPath: 'Создать план обучения', stepCounter: 'Шаг {step} из 4', selectGrade: 'Выберите класс, чтобы продолжить.', selectInterest: 'Выберите хотя бы один интерес.', selectGoal: 'Выберите хотя бы одну цель.',
    classJunior: '1–4 классы', classExplorer: '5–8 классы', classPro: '9–11 классы', gradeName: '{grade} класс', interestsProgramming: 'Программирование', interestsEnglish: 'Английский', interestsMath: 'Математика', interestsScience: 'Наука', interestsDesign: 'Дизайн', interestsBusiness: 'Бизнес', interestsCritical: 'Критическое мышление', interestsCommunication: 'Общение', interestsGeneral: 'Общие знания',
    goalGrades: 'Улучшить оценки', goalSkill: 'Освоить новый навык', goalCompetition: 'Подготовиться к соревнованиям', goalProgrammer: 'Стать программистом', goalEnglish: 'Улучшить английский', goalCareer: 'Подготовиться к будущей профессии',
    errorName: 'Введите полное имя.', errorUsername: 'Выберите имя пользователя.', errorEmail: 'Введите электронную почту.', errorEmailInvalid: 'Введите корректный адрес почты.', errorPassword: 'Используйте не менее 8 символов.', errorPasswordUpper: 'Добавьте хотя бы одну заглавную букву.', errorPasswordNumber: 'Добавьте хотя бы одну цифру.', errorConfirm: 'Подтвердите пароль.', errorPasswordMatch: 'Пароли не совпадают.', errorAgreement: 'Подтвердите согласие, чтобы продолжить.',
    mySpace: 'МОЁ ПРОСТРАНСТВО', discover: 'ОТКРЫВАЙТЕ', myJourney: 'МОЙ ПУТЬ', signOut: 'Выйти', welcomeBack: 'С возвращением', welcomeSubtitle: 'Продолжайте учиться, выполняйте квесты и создавайте своё будущее.', exploreTitle: 'Найдите то, что вас увлекает', exploreSubtitle: 'Выберите план обучения или начните подходящий квест.', questsTitle: 'Выберите следующее испытание', questsSubtitle: 'Практикуйте навыки, получайте XP и поддерживайте серию занятий.', newsTitle: 'Новости и идеи', newsSubtitle: 'Новые взгляды для вашего следующего учебного квеста.', leaderboardSubtitle: 'Отмечайте квесты, практику и каждый шаг вперёд.', achievementsSubtitle: 'Каждый значок отмечает навык, серию занятий или важный шаг.', profileSubtitle: 'Ваш прогресс, практика и достижения в одном месте.', progressSubtitle: 'Каждый завершённый квест укрепляет полезный навык.', searchTitle: 'Поиск в SkillQuest', searchSubtitle: 'Найдите квест или интересную идею для обучения.', browseQuests: 'Смотреть квесты', allQuests: 'Все квесты', all: 'Все', english: 'Английский', programming: 'Программирование', mathematics: 'Математика', science: 'Наука', design: 'Дизайн', business: 'Бизнес', generalSkills: 'Общие навыки', beginner: 'Начальный', intermediate: 'Средний', advanced: 'Продвинутый',
    settingsTitle: 'Настройки', settingsSubtitle: 'Настройте SkillQuest под свой стиль обучения.', profileDetails: 'Данные профиля', profileDetailsHelp: 'Измените имя, которое отображается в SkillQuest.', appearance: 'Внешний вид', appearanceHelp: 'Выберите комфортную цветовую схему для обучения.', language: 'Язык', languageHelp: 'Языковые настройки сохраняются на этом устройстве.', darkMode: 'Тёмная тема', lightMode: 'Светлая тема', saveProfile: 'Сохранить профиль', name: 'Полное имя', username: 'Имя пользователя', saved: 'Настройки сохранены.',
    helpTitle: 'Помощь и поддержка', helpSubtitle: 'Краткие ответы для вашего обучения.', helpNeed: 'Нужна помощь?', helpContactAdvice: 'По вопросам аккаунта или класса обратитесь к учителю или школьному администратору.', helpReviewSettings: 'Открыть настройки', faqQuestTitle: 'Как работают квесты?', faqQuestBody: 'Выберите предмет в своём плане обучения, откройте квест и отправьте ответ, чтобы получить XP и обновить прогресс.', faqStorageTitle: 'Где сохраняется мой прогресс?', faqStorageBody: 'Профиль, XP, серия занятий и завершённые квесты хранятся в браузере на этом устройстве.', faqPathTitle: 'Можно ли изменить план обучения?', faqPathBody: 'Да. Откройте план обучения в боковом меню, чтобы изменить класс, предметы, интересы и цель.', emptyNotifications: 'Уведомлений пока нет', clearNotifications: 'Очистить все', markRead: 'Отметить все как прочитанные', newsEducation: 'Образование', newsTechnology: 'Технологии', newsScience: 'Наука', newsProgramming: 'Программирование', newsEnglish: 'Английский', newsStudyTips: 'Советы по учёбе', readMore: 'Подробнее',
  },
}

export function readLanguage() {
  try {
    const value = localStorage.getItem(LANGUAGE_KEY)
    return Object.hasOwn(messages, value) ? value : 'en'
  } catch {
    return 'en'
  }
}