import { createContext } from 'react'

export const LANGUAGE_KEY = 'skillquest.language'

export const LanguageContext = createContext(null)

export const messages = {
  en: {
    home: 'My Learning Space', quests: 'My Quests', progress: 'Learning Progress', explore: 'Explore', news: 'News', leaderboard: 'Leaderboard', achievements: 'Achievements', learningPath: 'Learning Path', settings: 'Settings', help: 'Help & Support', search: 'Search', notifications: 'Notifications', profile: 'Profile',
    mySpace: 'MY SPACE', discover: 'DISCOVER', myJourney: 'MY JOURNEY', signOut: 'Sign out', welcomeBack: 'Welcome back', welcomeSubtitle: 'Keep learning, complete quests, and build your future.', exploreTitle: 'Find what sparks your curiosity', exploreSubtitle: 'Choose a learning path or jump into a quest that fits your momentum.', questsTitle: 'Choose your next challenge', questsSubtitle: 'Practice a skill, earn XP, and keep building your learning streak.', newsTitle: 'News & ideas', newsSubtitle: 'Fresh perspectives to fuel your next learning quest.', leaderboardSubtitle: 'Celebrate the quests, practice, and progress that add up.', achievementsSubtitle: 'Every badge marks a skill, streak, or moment of progress.', profileSubtitle: 'Your progress, practice, and milestones in one place.', progressSubtitle: 'Every completed quest builds a skill you can keep.', searchTitle: 'Search SkillQuest', searchSubtitle: 'Find a quest to try or an idea to explore.', browseQuests: 'Browse quests', allQuests: 'All quests', all: 'All', english: 'English', programming: 'Programming', mathematics: 'Mathematics', science: 'Science', design: 'Design', business: 'Business', generalSkills: 'General Skills', beginner: 'Beginner', intermediate: 'Intermediate', advanced: 'Advanced',
    settingsTitle: 'Settings', settingsSubtitle: 'Make SkillQuest work the way you learn.', profileDetails: 'Profile details', profileDetailsHelp: 'Update the name shown around SkillQuest.', appearance: 'Appearance', appearanceHelp: 'Choose a comfortable palette for your learning space.', language: 'Language', languageHelp: 'Your language preference is saved on this device.', darkMode: 'Dark mode', lightMode: 'Light mode', saveProfile: 'Save profile', name: 'Full name', username: 'Username', saved: 'Your settings have been saved.',
    helpTitle: 'Help & Support', helpSubtitle: 'Quick answers for your learning journey.', helpNeed: 'Need a hand?', helpContactAdvice: 'For account or classroom support, speak with your teacher or school administrator.', helpReviewSettings: 'Review settings', faqQuestTitle: 'How do quests work?', faqQuestBody: 'Choose a subject in your learning path, open a quest, and submit your answer to earn XP and update your progress.', faqStorageTitle: 'Where is my progress saved?', faqStorageBody: 'Your profile, XP, streak, and completed quests are stored locally in this browser on this device.', faqPathTitle: 'Can I change my learning path?', faqPathBody: 'Yes. Open Learning Path from the sidebar to update your grade, subjects, interests, and learning goal.', emptyNotifications: 'No notifications yet', clearNotifications: 'Clear all', markRead: 'Mark all as read', newsEducation: 'Education', newsTechnology: 'Technology', newsScience: 'Science', newsProgramming: 'Programming', newsEnglish: 'English', newsStudyTips: 'Study Tips', readMore: 'Read More',
  },
  uz: {
    home: 'Mening o‘quv makonim', quests: 'Mening questlarim', progress: 'O‘quv natijalari', explore: 'Kashf etish', news: 'Yangiliklar', leaderboard: 'Reyting', achievements: 'Yutuqlar', learningPath: 'O‘quv yo‘li', settings: 'Sozlamalar', help: 'Yordam', search: 'Qidirish', notifications: 'Bildirishnomalar', profile: 'Profil',
    mySpace: 'MENING MAKONIM', discover: 'KASHF ETISH', myJourney: 'MENING SAFARIM', signOut: 'Chiqish', welcomeBack: 'Qaytganingiz bilan', welcomeSubtitle: 'O‘rganishda davom eting, questlarni bajaring va kelajagingizni quring.', exploreTitle: 'Qiziqishingizni uyg‘otadigan yo‘nalishni toping', exploreSubtitle: 'O‘quv yo‘lini tanlang yoki hozirgi sur’atingizga mos questni boshlang.', questsTitle: 'Keyingi chaqiruvingizni tanlang', questsSubtitle: 'Ko‘nikma mashq qiling, XP oling va o‘quv zanjiringizni davom ettiring.', newsTitle: 'Yangiliklar va g‘oyalar', newsSubtitle: 'Keyingi o‘quv questingiz uchun yangi qarashlar.', leaderboardSubtitle: 'Questlar, mashqlar va o‘sish natijalarini nishonlang.', achievementsSubtitle: 'Har bir nishon ko‘nikma, davomiylik yoki yutuqni bildiradi.', profileSubtitle: 'O‘sish, mashqlar va yutuqlaringiz bir joyda.', progressSubtitle: 'Har bir bajarilgan quest kelajakda kerak bo‘ladigan ko‘nikmani mustahkamlaydi.', searchTitle: 'SkillQuest’dan qidiring', searchSubtitle: 'Quest yoki o‘rganishga oid g‘oyani toping.', browseQuests: 'Questlarni ko‘rish', allQuests: 'Barcha questlar', all: 'Barchasi', english: 'Ingliz tili', programming: 'Dasturlash', mathematics: 'Matematika', science: 'Fan', design: 'Dizayn', business: 'Biznes', generalSkills: 'Umumiy ko‘nikmalar', beginner: 'Boshlang‘ich', intermediate: 'O‘rta', advanced: 'Yuqori',
    settingsTitle: 'Sozlamalar', settingsSubtitle: 'SkillQuest’ni o‘rganish uslubingizga moslang.', profileDetails: 'Profil ma’lumotlari', profileDetailsHelp: 'SkillQuest’da ko‘rinadigan ismingizni yangilang.', appearance: 'Ko‘rinish', appearanceHelp: 'O‘quv makoningiz uchun qulay rang uslubini tanlang.', language: 'Til', languageHelp: 'Til tanlovi ushbu qurilmada saqlanadi.', darkMode: 'Tungi rejim', lightMode: 'Kunduzgi rejim', saveProfile: 'Profilni saqlash', name: 'To‘liq ism', username: 'Foydalanuvchi nomi', saved: 'Sozlamalar saqlandi.',
    helpTitle: 'Yordam va qo‘llab-quvvatlash', helpSubtitle: 'O‘quv safaringiz uchun qisqa javoblar.', helpNeed: 'Yordam kerakmi?', helpContactAdvice: 'Hisob yoki sinf bo‘yicha yordam uchun o‘qituvchingiz yoki maktab ma’muriga murojaat qiling.', helpReviewSettings: 'Sozlamalarni ko‘rish', faqQuestTitle: 'Questlar qanday ishlaydi?', faqQuestBody: 'O‘quv yo‘lingizdan fan tanlang, questni oching va XP hamda progress olish uchun javob yuboring.', faqStorageTitle: 'Progressim qayerda saqlanadi?', faqStorageBody: 'Profil, XP, streak va bajarilgan questlar ushbu qurilmadagi brauzerda saqlanadi.', faqPathTitle: 'O‘quv yo‘limni o‘zgartira olamanmi?', faqPathBody: 'Ha. Sinf, fanlar, qiziqishlar va maqsadni o‘zgartirish uchun yon menyudan O‘quv yo‘lini oching.', emptyNotifications: 'Hozircha bildirishnomalar yo‘q', clearNotifications: 'Hammasini tozalash', markRead: 'Hammasini o‘qilgan deb belgilash', newsEducation: 'Ta’lim', newsTechnology: 'Texnologiya', newsScience: 'Fan', newsProgramming: 'Dasturlash', newsEnglish: 'Ingliz tili', newsStudyTips: 'O‘qish bo‘yicha maslahatlar', readMore: 'Batafsil',
  },
  ru: {
    home: 'Моё обучение', quests: 'Мои квесты', progress: 'Мой прогресс', explore: 'Обзор', news: 'Новости', leaderboard: 'Рейтинг', achievements: 'Достижения', learningPath: 'План обучения', settings: 'Настройки', help: 'Помощь', search: 'Поиск', notifications: 'Уведомления', profile: 'Профиль',
    mySpace: 'МОЁ ПРОСТРАНСТВО', discover: 'ОТКРЫВАЙТЕ', myJourney: 'МОЙ ПУТЬ', signOut: 'Выйти', welcomeBack: 'С возвращением', welcomeSubtitle: 'Продолжайте учиться, выполняйте квесты и создавайте своё будущее.', exploreTitle: 'Найдите то, что вас увлекает', exploreSubtitle: 'Выберите план обучения или начните подходящий квест.', questsTitle: 'Выберите следующее испытание', questsSubtitle: 'Практикуйте навыки, получайте XP и поддерживайте серию занятий.', newsTitle: 'Новости и идеи', newsSubtitle: 'Новые взгляды для вашего следующего учебного квеста.', leaderboardSubtitle: 'Отмечайте квесты, практику и каждый шаг вперёд.', achievementsSubtitle: 'Каждый значок отмечает навык, серию занятий или важный шаг.', profileSubtitle: 'Ваш прогресс, практика и достижения в одном месте.', progressSubtitle: 'Каждый завершённый квест укрепляет полезный навык.', searchTitle: 'Поиск в SkillQuest', searchSubtitle: 'Найдите квест или интересную идею для обучения.', browseQuests: 'Смотреть квесты', allQuests: 'Все квесты', all: 'Все', english: 'Английский', programming: 'Программирование', mathematics: 'Математика', science: 'Наука', design: 'Дизайн', business: 'Бизнес', generalSkills: 'Общие навыки', beginner: 'Начальный', intermediate: 'Средний', advanced: 'Продвинутый',
    settingsTitle: 'Настройки', settingsSubtitle: 'Настройте SkillQuest под свой стиль обучения.', profileDetails: 'Данные профиля', profileDetailsHelp: 'Измените имя, которое отображается в SkillQuest.', appearance: 'Внешний вид', appearanceHelp: 'Выберите комфортную цветовую схему для обучения.', language: 'Язык', languageHelp: 'Языковые настройки сохраняются на этом устройстве.', darkMode: 'Тёмная тема', lightMode: 'Светлая тема', saveProfile: 'Сохранить профиль', name: 'Полное имя', username: 'Имя пользователя', saved: 'Настройки сохранены.',
    helpTitle: 'Помощь и поддержка', helpSubtitle: 'Краткие ответы для вашего обучения.', helpNeed: 'Нужна помощь?', helpContactAdvice: 'По вопросам аккаунта или класса обратитесь к учителю или школьному администратору.', helpReviewSettings: 'Открыть настройки', faqQuestTitle: 'Как работают квесты?', faqQuestBody: 'Выберите предмет в своём плане обучения, откройте квест и отправьте ответ, чтобы получить XP и обновить прогресс.', faqStorageTitle: 'Где сохраняется мой прогресс?', faqStorageBody: 'Профиль, XP, серия занятий и завершённые квесты хранятся в браузере на этом устройстве.', faqPathTitle: 'Можно ли изменить план обучения?', faqPathBody: 'Да. Откройте план обучения в боковом меню, чтобы изменить класс, предметы, интересы и цель.', emptyNotifications: 'Уведомлений пока нет', clearNotifications: 'Очистить все', markRead: 'Отметить все как прочитанные', newsEducation: 'Образование', newsTechnology: 'Технологии', newsScience: 'Наука', newsProgramming: 'Программирование', newsEnglish: 'Английский', newsStudyTips: 'Советы по учёбе', readMore: 'Подробнее',
  },
}

export function readLanguage() {
  try {
    const value = localStorage.getItem(LANGUAGE_KEY)
    return Object.hasOwn(messages, value) ? value : 'en'
  } catch {
    return 'en'
  }
}